language: python
python:
  -"3.7"
  
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
services:
  -docker

before-script: pip instal doker-compose

script:
  -docker-compose run app sh - c "python manage.py test && flakes"

