language: python
python:
  -"3.7"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
services:
  - docker

before-script: pip install docker-compose

script:
  - docker-compose run --rm app sh - c "python manage.py test && flake8"

